# Generated by Django 4.2 on 2023-04-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='ingredients',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blog',
            name='procedure',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
