# Generated by Django 4.2 on 2023-04-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_blog_ingredients_blog_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(max_length=2555),
        ),
        migrations.AlterField(
            model_name='blog',
            name='procedure',
            field=models.TextField(blank=True, max_length=2555),
        ),
    ]
